blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

bug_issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('bugs/', include('bugs.urls')),
    path('features/', include('features.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
]

cart/urls.py
from django.urls import path
from .views import view_cart, add_to_cart, adjust_cart
app_name = 'cart'

urlpatterns = [
	path('', view_cart, name='view_cart'),
	path('<int:id>/add/', add_to_cart, name='add_to_cart'),
	path('<int:id>/adjust/', adjust_cart, name='adjust_cart'),
]

checkout/urls.py
from django.urls import path
from .views import checkout

app_name = 'checkout'

urlpatterns = [
	path('', checkout, name='checkout'),
]

cart/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required()
def view_cart(request):
	"""
	Renders the cart content page
	"""
	return render(request, "cart/cart.html")

@login_required()
def add_to_cart(request, id):
    """Add a quantity of the specified product to the cart"""
    quantity = 1

    cart = request.session.get('cart', {})
    if id in cart:
        print(cart)
        cart[id] = int(cart[id]) + quantity      
    else:
        cart[id] = cart.get(id, quantity) 

    request.session['cart'] = cart
    return redirect(reverse('cart:view_cart'))

@login_required()
def adjust_cart(request, id):
    """
    Delete the Feature from the cart
    """
    
    
    cart = request.session.get('cart', {})

    cart.pop(str(id))

    request.session['cart'] = cart
    return redirect(reverse('cart:view_cart'))

templates/cart/cart.html
{% extends 'base.html' %}
{% block page_title %} Cart {% endblock %}
{% load static from staticfiles %}
{% block content %}
<div class="container">
    {% if cart_items %}
    <div class="row blog-cust mt-5">     
        <div class="col-xs-12 col-sm-10 col-md-10 offset-md-1 p-0">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Product Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        
                    </tr>
                </thead>
                {% for item in cart_items %}
                <tbody>
                    <tr>
                        <td>{{ item.product.title }}</td>
                        <td>{{ item.product.price }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>
                            <form class="form-inline" method="post" action="{% url 'cart:adjust_cart' item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>Remove from cart</button>
                            </form>
                        </td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="row blog-cust m-5 p-5">
        <div class="col-md-6 offset-md-4">
            <span>Total £ {{ total }}</span>
            <span><a href="{% url 'checkout:checkout' %}" class="btn btn-success" role="button">Checkout</a></span>
        </div>
    </div>
    {% else %}
    <div class="row blog-cust">
        <div class="col-md-6 text-center offset-md-3 m-5 p-5">
            <p>Nothing in your cart yet!</p>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}