blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

bug_issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('bugs/', include('bugs.urls')),
    path('features/', include('features.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
]

bugs/urls.py
from django.urls import path
from . import views
from .views import bugs_list, bug_detail, bug_add, bug_delete, bug_edit, bug_likes

app_name = 'bugs'

urlpatterns = [
	path('bugs_list/', bugs_list, name='bugs_list'),
	path('<int:pk>/', bug_detail, name='bug_detail'),
	path('bug_add/', bug_add, name='bug_add'),
	path('<int:pk>/bug_delete/', bug_delete, name='bug_delete'),
	path('<int:pk>/bug_edit/', bug_edit, name='bug_edit'),
	path('likes/<int:pk>/', bug_likes, name='bug_likes'),
]

bugs/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User






class Bug(models.Model):

	"""
	Creates a bug post model on the database
	"""

	Received = 'Received'
	In_progress = 'In progress'
	Done = 'Done'

	CHOICES = [
		(Received, 'Received'),
		(In_progress, 'In progress'),
		(Done, 'Done')
	]

	title = models.CharField(max_length=200, unique=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bug_report')
	content = models.TextField()
	likes = models.IntegerField(default=0)
	created_on = models.DateTimeField(auto_now_add=True)
	status = models.CharField(max_length=15 ,choices=CHOICES, default=Received)
	views = models.IntegerField(default=0)

	class Meta:
		ordering = ['-created_on']

	def get_absolute_url(self):
		return "bugs/%d/%s"%(self.id, self.title)

	def __str__(self):
		return self.title

"""class BugLikes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bug = models.ForeignKey(Bug, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def view_count(self):
        return BugLikes.objects.filter(bug=self).count()"""
	
class Comment(models.Model):
	"""
	Creates a comment model on the database
	"""
	bug = models.ForeignKey(Bug, on_delete=models.CASCADE, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=False)

	class Meta:
		ordering = ['created_on']

	def __str__(self):
		return 'Comment {} by {}'.format(self.body, self.name)

bugs/forms.py
from django import forms
from .models import Bug, Comment

class BugPostForm(forms.ModelForm):
	class Meta:
		model = Bug
		fields = ('title', 'content')

class BugCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

bugs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from .models import Bug, Comment
from .forms import BugCommentForm, BugPostForm



def bugs_list(request):
	"""
	This view will list all bugs starting with the most recent ones
	"""
	bugs = Bug.objects.order_by('-created_on').all()
	paginator = Paginator(bugs, 4)
	page = request.GET.get('page')
	bugs = paginator.get_page(page)
	return render(request, 'bugs/bugs.html', {'bugs': bugs})

def bug_detail(request, pk):
	"""
	This view allow users to see a specific bug report in a separate window
	and also to add comments to it
	"""
	# Retrive bug details
	bug = get_object_or_404(Bug, pk=pk)
	bug.views += 1
	bug.save()
	comments = bug.comments.filter(active=True)
	new_comment = None
	# Comments functionality *** credit for the code to https://djangocentral.com
	if request.method == 'POST':
		comment_form = BugCommentForm(data=request.POST)
		if comment_form.is_valid:
			new_comment = comment_form.save(commit=False)
			new_comment.bug = bug
			new_comment.save()
	else:
		comment_form = BugCommentForm
	return render(request, 'bugs/bug_detail.html', {'bug': bug, 
											'comments': comments,
											'new_comment': new_comment,
											'comment_form': comment_form})


@login_required
def bug_likes(request, pk):
	"""
	This view allow users to like bug reports
	"""
	bug = get_object_or_404(Bug, pk=pk)
	bug.likes += 1
	bug.save()

	return redirect('bugs:bug_detail', pk=bug.pk)


@login_required
def bug_add(request):
	"""
	This view allow users to submit their bug reports
	"""
	if request.method == 'POST':
		bug_form = BugPostForm(request.POST)
		if bug_form.is_valid:
			bug = bug_form.save(commit=False)
			bug.author = request.user
			bug.save()
			messages.success(request, 'Successfully created!')
			return redirect('bugs:bug_detail', pk=bug.pk)
	else:
		bug_form = BugPostForm()
	return render(request, 'bugs/bug_add.html', {'bug_form': bug_form})


@login_required
def bug_delete(request, pk):
	"""
	This view allow a user to delete a bug report, but only if is the author 
	"""
	bug = get_object_or_404(Bug, pk=pk)
	if request.user == bug.author:
		bug.delete()
		messages.success(request, 'Successfully deleted!')
	else:
		messages.error(request, 'You can\'t delete this!')
		return redirect('bugs:bug_detail', pk=bug.pk)

	return redirect('bugs:bugs_list')


@login_required
def bug_edit(request, pk):
	"""
	This view allow users to edit a previously submited bug report
	"""
	bug = get_object_or_404(Bug, pk=pk)
	if request.user == bug.author:
		if request.method == "POST":
			bug_form = BugPostForm(request.POST, instance=bug)
			if bug_form.is_valid:
				bug_form.save()
				return redirect('bugs:bug_detail', pk=bug.pk)
		else:
			bug_form = BugPostForm(instance=bug)
		return render(request, "bugs/bug_add.html", {"bug_form": bug_form})
	else:
		messages.error(request, 'You can\'t edit this!')
		bug_form = BugPostForm()
	return redirect('bugs:bug_detail', pk=bug.pk)

templates/bugs/bug_add.html
{% extends 'base.html' %} 
{% block page_title %} Submit Your Bug Here{% endblock %}
{% block content %}
{% load crispy_forms_tags %}



<div class="container ">
    <div class="row mt-5">
    	<div class="col-md-8">
        	<div class="card-body card-color">
        	    <h3>Submit Your Bug Here</h3>
        	    <form method="post" style="margin-top: 1.3em;">
        	        {{ bug_form | crispy }}
        	        {% csrf_token %}
        	        <button type="submit" class="btn btn-secondary  btn-lg">Submit</button>
                    <span><a href="{% url 'bugs:bugs_list' %}" class="btn btn-danger ">Cancel</a></span>
        	    </form>
        	</div>
        </div>

        {% block sidebar %} 
  			{% include 'sidebar.html' %} 
		{% endblock sidebar %}

    </div>
</div>

{% endblock %}

templates/bugs/bug_detail.html
{% extends 'base.html' %}
{% block page_title %} Bug Detail{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

{% block feedback_messages %} {% include 'feedbackmessages.html' %} {% endblock feedback_messages %}

<div class="container">
  <div class="row">

    <div class="col-md-12">
      <span><a href="{% url 'bugs:bugs_list' %}" class="btn btn-secondary mt-3">&larr; Back to bugs page</a></span>
    </div>

    <!-- Bug Details -->
    <div class="col-md-8 card mb-4  mt-3 left top card-color">
      <div class="card-body ">
        <h2><b>{{ bug.title }}</b>
        {% if bug.status == 'Received' %}
          <span class="alert alert-info"><i>Status: </i><b>{{ bug.status }}</b></span>
        {% elif bug.status == 'In progress' %}
          <span class="alert alert-primary"><i>Status: </i><b>{{ bug.status }}</b></span>
        {% else %}
          <span class="alert alert-success"><i>Status: </i><b>{{ bug.status }}</b></span>
        {% endif %}
        </h2>
        <br>
        <p class=" text-muted">Posted by <b>{{ bug.author }}</b> on <b>{{ bug.created_on|date:"M d, Y" }}</b> at <b>{{bug.created_on|time:"h:i a"}}</b></p>
        
        <hr/>
        <p class="card-text">{{ bug.content | safe }}</p>
        <hr/>
        <!-- *** -->

        <!-- LIKE -->
        <div class="row">
          <div class="col-xs-1 col-sm-10 col-md-10">
            <form class="icon-cust" method="post" action="{% url 'bugs:bug_likes' bug.id %}">
              {% csrf_token %}
              <button type="submit" name="bug_id" value="{{ bug.id }}" class="btn btn-primary rounded-circle"><i class="far fa-thumbs-up"></i></button>
              <small>{{ bug.likes }}</small>
            </form>
          </div>
        <!-- *** -->
  
          <!-- Delete & Edit -->
          <div class="col-xs-1 col-sm-1 col-md-1">
            <span><i class="fas fa-trash-alt icon-cust" data-toggle="modal" data-target="#deleteBugModal{{bug.id}}"></i></span>
          </div>
          <div class="col-xs-1 col-sm-1 col-md-1">
            <span><a href="{% url 'bugs:bug_edit' bug.id %}"><i class="fas fa-edit icon-cust"></i></a></span>
          </div>
        </div>
      </div>
      <!-- *** -->

      <!--Popup modal for confirming bug delete-->
      <div class="modal" id="deleteBugModal{{bug.id}}" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ bug.title}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger"><a class="btn btn-delete text-white" href="{% url 'bugs:bug_delete' bug.pk %}">
                        Delete
                    </a></button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
      </div>
      <!-- *** -->
    
      <div class="card-body border border-dark rounded border-dark">
        
        <!-- comments -->
        {% with comments.count as total_comments %}
          <h2>{{ total_comments }} comments</h2>
          <hr/>
        {% endwith %}
         
        {% for comment in comments %}
       

        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }} |
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          
          {{ comment.body | linebreaks }}
          <hr/>
        </div>

        {% endfor %}
      </div>
    
    {% if user.is_authenticated %}
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <hr/>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    {% endif %}

  </div>
  {% if user.is_authenticated %}
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  {% endif %}
</div>

{% endblock content %}
    

templates/bugs/bugs.html
{% extends "base.html" %} 
{% block page_title %} Bugs Home{% endblock %}
{% block content %}



{% block feedback_messages %} {% include 'feedbackmessages.html' %} {% endblock feedback_messages %}
<div class="body-bg">
    <div class="container">
        <a href="{% url 'bugs:bug_add' %}" class="btn btn-secondary mt-3">Report a Bug &rarr;</a>
    </div>
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for bug in bugs %}
                <div class="card mb-4">
                    <div class="card-body card-color">
                        <h2 class="card-title"><b>{{ bug.title }}</b>
                            {% if bug.status == 'Received' %}
                            <span class="alert alert-info"><i>Status: </i><b>{{ bug.status }}</b></span>
                            {% elif bug.status == 'In progress' %}
                            <span class="alert alert-primary"><i>Status: </i><b>{{ bug.status }}</b></span>
                            {% else %}
                            <span class="alert alert-success"><i>Status: </i><b>{{ bug.status }}</b></span>
                            {% endif %}
                        </h2>
                        <p class="card-text text-muted h6">{{ bug.author }} <b>on</b> {{ bug.created_on|date:"M d, Y" }} </p>
                        <hr/>
                        <p class="card-text">{{bug.content|slice:":100" }}</p>
                        <a href="{% url 'bugs:bug_detail' pk=bug.pk %}" class="btn btn-outline-dark">Read More &rarr;</a>
                        <span class="views mr-1 pl-1"> {{ bug.views }} <i class="fas fa-eye"></i></span>
                        <span class="views mr-1">{{ bug.likes }} <i class="fas fa-thumbs-up"></i></span>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
                {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
            {% endif %}
        </div>
        <div class="pagination">
            {% if bugs.has_previous %}
                <a class="btn btn-secondary" href="?page=1">First</a>
                <a class="btn btn-secondary" href="?page={{ features.previous_page_number }}">&lt;</a>
            {% endif %}
            {% for num in bugs.paginator.page_range %}
                {% if bugs.number == num %}
                    <a class="btn btn-secondary" href="?page={{ bugs.number }}"> {{ bugs.number }}</a>
                    {% elif num > bugs.number|add:'-2' and num < bugs.number|add:'2' %} <a class="btn btn-secondary" href="?page={{ num }}"> {{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if bugs.has_next %}
                <a class="btn btn-secondary" href="?page={{ features.previous_page_number }}">&gt;</a>
                <a class="btn btn-secondary" href="?page={{ bugs.paginator.num_pages }}">last</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}