blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

bug_issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('bugs/', include('bugs.urls')),
    path('features/', include('features.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
]

cart/urls.py
from django.urls import path
from .views import view_cart, add_to_cart, adjust_cart
app_name = 'cart'

urlpatterns = [
	path('', view_cart, name='view_cart'),
	path('<int:id>/add/', add_to_cart, name='add_to_cart'),
	path('<int:id>/adjust/', adjust_cart, name='adjust_cart'),
]

features/urls.py
from django.urls import path

from .views import features_list, feature_detail, feature_add, feature_delete, feature_edit

app_name = 'features'

urlpatterns = [
	path('features_list/', features_list, name='features_list'),
	path('<int:pk>/', feature_detail, name='feature_detail'),
	path('feature_add/', feature_add, name='feature_add'),
	path('<int:pk>/feature_delete/', feature_delete, name='feature_delete'),
	path('<int:pk>/feature_edit/', feature_edit, name='feature_edit'),
]

features/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import User






class Feature(models.Model):

	"""
	Creates a Feature post model on the database
	"""

	Received = 'Received'
	In_progress = 'In progress'
	Done = 'Done'

	CHOICES = [
		(Received, 'Received'),
		(In_progress, 'In progress'),
		(Done, 'Done')
	]

	title = models.CharField(max_length=200, unique=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feature_report')
	content = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)
	status = models.CharField(max_length=15 ,choices=CHOICES, default=Received)
	views = models.IntegerField(default=0)
	price = models.DecimalField(max_digits=6, decimal_places=2, default=10.00)

	class Meta:
		ordering = ['-created_on']

	def __str__(self):
		return self.title


	
class Comment(models.Model):
	"""
	Creates a comment model on the database
	"""
	feature = models.ForeignKey(Feature, on_delete=models.CASCADE, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=False)

	class Meta:
		ordering = ['created_on']

	def __str__(self):
		return 'Comment {} by {}'.format(self.body, self.name)

features/forms.py
from django import forms
from .models import Feature, Comment

class FeaturePostForm(forms.ModelForm):
	class Meta:
		model = Feature
		fields = ('title', 'content')

class FeatureCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

features/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from .models import Feature, Comment
from .forms import FeatureCommentForm, FeaturePostForm



def features_list(request):
	"""
	This view will list all bugs starting with the most recent ones
	"""
	features = Feature.objects.order_by('-created_on').all()
	paginator = Paginator(features, 4)
	page = request.GET.get('page')
	features = paginator.get_page(page)
	return render(request, 'features/features.html', {'features': features})


def feature_detail(request, pk):
	"""
	This view allow users to see a specific bug report in a separate window
	and also to add comments to it
	"""
	# Retrive bug details
	feature = get_object_or_404(Feature, pk=pk)
	feature.views += 1
	feature.save()
	comments = feature.comments.filter(active=True)
	new_comment = None
	# Comments functionality *** credit for the code to https://djangocentral.com
	if request.method == 'POST':
		comment_form = FeatureCommentForm(data=request.POST)
		if comment_form.is_valid:
			new_comment = comment_form.save(commit=False)
			new_comment.feature = feature
			new_comment.save()
	else:
		comment_form = FeatureCommentForm
	return render(request, 'features/feature_detail.html', {'feature': feature, 
												'comments': comments,
												'new_comment': new_comment,
												'comment_form': comment_form})

@login_required
def feature_add(request):
	"""
	This view allow users to submit their bug reports
	"""
	if request.method == 'POST':
		feature_form = FeaturePostForm(request.POST)
		if feature_form.is_valid:
			feature = feature_form.save(commit=False)
			feature.author = request.user
			feature.save()
			messages.success(request, 'Successfully created!')
			return redirect('features:feature_detail', pk=feature.pk)
	else:
		feature_form = FeaturePostForm()
	return render(request, 'features/feature_add.html', {'feature_form': feature_form})



@login_required
def feature_delete(request, pk):
	"""
	This view allow a user to delete a bug report, but only if is the author 
	"""
	feature = get_object_or_404(Feature, pk=pk)
	if request.user == feature.author:
		feature.delete()
		messages.success(request, 'Successfully deleted!')
	else:
		messages.error(request, 'You can\'t delete this!')
		return redirect('features:feature_detail', pk=feature.pk)

	return redirect('features:features_list')


@login_required
def feature_edit(request, pk):
	"""
	This view allow users to edit a previously submited bug report
	"""
	feature = get_object_or_404(Feature, pk=pk)
	if request.user == feature.author:
		if request.method == "POST":
			feature_form = FeaturePostForm(request.POST, instance=feature)
			if feature_form.is_valid:
				feature_form.save()
				return redirect('features:feature_detail', pk=feature.pk)
		else:
			feature_form = FeaturePostForm(instance=feature)
		return render(request, "features/feature_add.html", {"feature_form": feature_form})
	else:
		messages.error(request, 'You can\'t edit this!')
		feature_form = FeaturePostForm()
	return redirect('features:feature_detail', pk=feature.pk)

templates/features/feature_add.html
{% extends 'base.html' %} 
{% block page_title %} Submit Your Feature Request Here {% endblock %}
{% block content %}
{% load crispy_forms_tags %}



<div class="container">
    <div class="row mt-5">
    	<div class="col-md-8">
        	<div class="card-body card-color">
        	    <h3>Submit Your Feature Request Here</h3>
        	    <form method="post" style="margin-top: 1.3em;">
        	        {{ feature_form | crispy }}
        	        {% csrf_token %}
        	        <button type="submit" class="btn btn-secondary  btn-lg">Submit</button>
                    <span><a href="{% url 'features:features_list' %}" class="btn btn-danger ">Cancel</a></span>
        	    </form>
        	</div>
        </div>

        {% block sidebar %} 
  			{% include 'sidebar.html' %} 
		{% endblock sidebar %}

    </div>
</div>

{% endblock %}

templates/features/feature_detail.html
{% extends 'base.html' %}
{% block page_title %} Feature Details {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% block feedback_messages %} {% include 'feedbackmessages.html' %} {% endblock feedback_messages %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <span><a href="{% url 'features:features_list' %}" class="btn btn-secondary mt-3">&larr; Back to Features page</a></span>
        </div>
        <!-- Feature Details -->
        <div class="col-md-8 card mb-4  mt-3 left top card-color">
            <div class="card-body ">
                <h2><b>{{ feature.title }}</b>
                    {% if feature.status == 'Received' %}
                    <span class="alert alert-info"><i>Status: </i><b>{{ feature.status }}</b></span>
                    {% elif feature.status == 'In progress' %}
                    <span class="alert alert-primary"><i>Status: </i><b>{{ feature.status }}</b></span>
                    {% else %}
                    <span class="alert alert-success"><i>Status: </i><b>{{ feature.status }}</b></span>
                    {% endif %}
                </h2>
                <br />
                <p class=" text-muted">Posted by <b>{{ feature.author }}</b> on <b>{{ feature.created_on|date:"M d, Y" }}</b> at <b>{{feature.created_on|time:"h:i a"}}</b></p>
                <br>
                <p class="card-text">{{ feature.content | safe }}</p>
                <hr />
                <!-- *** -->
                <!-- LIKE -->
                <div class="row">
                
                    <!-- *** -->
                    <!-- Delete & Edit -->
                    <div class="col-xs-1 col-sm-1 col-md-1">
                        <span><i class="fas fa-trash-alt icon-cust" data-toggle="modal" data-target="#deleteFeatureModal{{feature.id}}"></i></span>
                    </div>
                    <div class="col-xs-1 col-sm-1 col-md-1">
                        <span><a href="{% url 'features:feature_edit' feature.id %}"><i class="fas fa-edit icon-cust"></i></a></span>
                    </div>
                </div>
            </div>
            <!-- *** -->
            <!--Popup modal for confirming bug delete-->
            <div class="modal" id="deleteFeatureModal{{feature.id}}" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">{{ feature.title}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to delete this?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger"><a class="btn btn-delete text-white" href="{% url 'features:feature_delete' feature.pk %}">
                                    Delete
                                </a></button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            <form method="post" class="pb-3" action="{% url 'cart:add_to_cart' feature.id %}">
                {% csrf_token %}
                <div class="input-group">
                    <span class="input-group-btn">
                        <button class="btn btn-success" type="submit">Add to cart</button>
                    </span>
                </div>
            </form>
            <!-- *** -->
            <div class="card-body border border-dark rounded border-dark">
                <!-- comments -->
                {% with comments.count as total_comments %}
                <h2>{{ total_comments }} comments</h2>
                {% endwith %}
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }} |
                        <span class=" text-muted font-weight-normal">
                            {{ comment.created_on }}
                        </span>
                    </p>
                    {{ comment.body | linebreaks }}
                    <hr />
                </div>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
            <div class="card-body">
                {% if new_comment %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting moderation
                </div>
                {% else %}
                <h3>Leave a comment</h3>
                <hr />
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary btn-lg">Submit</button>
                </form>
                {% endif %}
            </div>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/features/features.html
{% extends "base.html" %}
{% block page_title %} Features Home {% endblock %}
{% block content %}
{% block feedback_messages %} {% include 'feedbackmessages.html' %} {% endblock feedback_messages %}
<div class="container">
    <a href="{% url 'features:feature_add' %}" class="btn btn-secondary mt-3">Request a Feature &rarr;</a>
</div>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for feature in features %}
            <div class="card mb-4">
                <div class="card-body card-color">
                    <h2 class="card-title"><b>{{ feature.title }}</b>
                        <span class="alert alert-warning">Price: <i class="fas fa-pound-sign"></i>{{ feature.price }}</span>
                        {% if feature.status == 'Received' %}
                        <span class="alert alert-info"><i>Status: </i><b>{{ feature.status }}</b></span>
                        {% elif feature.status == 'In progress' %}
                        <span class="alert alert-primary"><i>Status: </i><b>{{ feature.status }}</b></span>
                        {% else %}
                        <span class="alert alert-success"><i>Status: </i><b>{{ feature.status }}</b></span>
                        {% endif %}
                    </h2>
                    <p class="card-text text-muted h6">{{ feature.author }} <b>on</b> {{ feature.created_on|date:"M d, Y" }} </p>
                    <p class="card-text">{{feature.content|slice:":100" }}</p>
                    <a href="{% url 'features:feature_detail' pk=feature.pk %}" class="btn btn-outline-dark">Read More &rarr;</a>
                    <span class="views">{{ feature.views }} <i class="fas fa-eye"></i></span>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if user.is_authenticated %}
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
        {% endif %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if features.has_previous %}
            <a class="btn btn-secondary" href="?page=1">&laquo; first</a>
            <a class="btn btn-secondary" href="?page={{ features.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current alert alert-secondary small">
                Page {{ features.number }} of {{ features.paginator.num_pages }}.
            </span>
            {% if features.has_next %}
            <a class="btn btn-secondary" href="?page={{ features.next_page_number }}">next</a>
            <a class="btn btn-secondary" href="?page={{ features.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}