blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

bug_issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('bugs/', include('bugs.urls')),
    path('features/', include('features.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
]

bugs/urls.py
from django.urls import path
from . import views
from .views import bugs_list, bug_detail, bug_add, bug_delete, bug_edit, bug_likes

app_name = 'bugs'

urlpatterns = [
	path('bugs_list/', bugs_list, name='bugs_list'),
	path('<int:pk>/', bug_detail, name='bug_detail'),
	path('bug_add/', bug_add, name='bug_add'),
	path('<int:pk>/bug_delete/', bug_delete, name='bug_delete'),
	path('<int:pk>/bug_edit/', bug_edit, name='bug_edit'),
	path('likes/<int:pk>/', bug_likes, name='bug_likes'),
]

cart/urls.py
from django.urls import path
from .views import view_cart, add_to_cart, adjust_cart
app_name = 'cart'

urlpatterns = [
	path('', view_cart, name='view_cart'),
	path('<int:id>/add/', add_to_cart, name='add_to_cart'),
	path('<int:id>/adjust/', adjust_cart, name='adjust_cart'),
]

features/urls.py
from django.urls import path

from .views import features_list, feature_detail, feature_add, feature_delete, feature_edit

app_name = 'features'

urlpatterns = [
	path('features_list/', features_list, name='features_list'),
	path('<int:pk>/', feature_detail, name='feature_detail'),
	path('feature_add/', feature_add, name='feature_add'),
	path('<int:pk>/feature_delete/', feature_delete, name='feature_delete'),
	path('<int:pk>/feature_edit/', feature_edit, name='feature_edit'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block page_title %} {% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head_js %} {% endblock head_js %}
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary" id="mainNav">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}"><i class="nav-logo fas fa-spider"> Bugs & Features </i> <i class="nav-logo fas fa-tools"></i></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold nav-font" href="{% url 'index' %}"><i class="fas fa-home"></i> Home |</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold nav-font" href="{% url 'features:features_list' %}"><i class="fas fa-tools"></i> Features |</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold nav-font" href="{% url 'bugs:bugs_list' %}"><i class="fas fa-bug"></i> Bugs |</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold nav-font" href="{% url 'blog:blog' %}"><i class="fas fa-blog"></i> Blog |</a>
                    </li>
                    {% if user.is_authenticated %}
                    {% if product_count > 0 %}
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold nav-font" href="{% url 'cart:view_cart' %}"><i class="fas fa-shopping-cart"></i> Cart <span class="badge badge-light">{{ product_count }}</span> |</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold nav-font" href="{% url 'cart:view_cart' %}"><i class="fas fa-shopping-cart"></i> Cart |</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold nav-font" href="{% url 'logout' %}"><i class="fas fa-power-off"></i> Logout |</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold nav-font" href="{% url 'register' %}"><i class="fas fa-user-plus"></i> Register |</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold nav-font" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> Log In |</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <main>
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
    </main>
    <!-- Footer -->
    <footer id="footer" class="page-footer fixed-bottom font-small bg-secondary">
        <div class="container">
            <div class="row">
                <div class="col-md-12 pt-1">
                    <div class="flex-center">
                        <a class="fa-lg mr-md-5 mr-3 fa-1x col-font" href="{% url 'index' %}"><i class="fas fa-home"></i> Home</a>
                        <a class="fa-lg mr-md-5 mr-3 fa-1x col-font" href="{% url 'features:features_list' %}"><i class="fas fa-tools"></i> Features</a>
                        <a class="fa-lg mr-md-5 mr-3 fa-1x col-font" href="{% url 'bugs:bugs_list' %}"><i class="fas fa-bug"></i> Bugs</a>
                        <a class="fa-lg mr-md-5 mr-3 fa-1x col-font" href="{% url 'blog:blog' %}"><i class="fas fa-blog"></i> Blog</a>
                    </div>
                    <hr />
                </div>
            </div>
            <div class="footer-copyright text-center pb-1">
                <small class="col-font">© 2020 Copyright: Marius G. Dumitru | Final project for <a class="col-font" href="https://codeinstitute.net/">Code Institute</a></small>
            </div>
        </div>
    </footer>
    <!-- Footer -->
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
    <script type="text/javascript" src="{% static 'js/chart.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    
</body>

</html>

templates/charts.html
{% block masthead %}
<div class="container-fluid">
    <div class="row blog-cust pt-3 pb-3">
        <div class="col-md-4">
            <h5 class="text-center">Bugs and Features</h5>
            <canvas id="myChart"></canvas>
        </div>
        <div class="col-md-4">
            <h5 class="text-center">Bugs By Status</h5>
            <canvas id="myChart2"></canvas>
        </div>
        <div class="col-md-4">
            <h5 class="text-center">Features By Status</h5>
            <canvas id="myChart3"></canvas>
        </div>
    </div>
</div>
{% endblock masthead %}
<!--<header class="masthead">
    <div class="container">
        <div class="row">
            <div class="col-md-3 mx-auto">
                <span><i class="fas fa-bug f-size"></i></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 mx-auto">
                <div class="site-heading">
                    <span>Bugs</span>
                </div>
            </div>
        </div>
    </div>
</header>-->

templates/feedbackmessages.html
{% block feedback_messages %}

<div class="container">
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block page_title %} HOME {% endblock %}

{% block head_js %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>

{% endblock head_js %}

{% block content %}
{% block feedback_messages %} {% include 'feedbackmessages.html' %} {% endblock feedback_messages %}
<div class="container-fluid">
    <div class="row">
        <!-- Features section -->
        <div class="col-md-5">
            <div class="card my-4">
                <h5 class="card-header text-center"><a class="nav-link font-weight-bold nav-font" href="{% url 'features:features_list' %}">Latest Features Posted <i class="fas fa-tools"></i></a></h5>
                <section class="alert alert_introduction alert-dismissible col-xs-12" role="alert">
                    <i class="fas fa-info-circle"></i>
                    <p>Features have a fiexd development cost of £10. To get a Feature simply add it to your cart, pay for it, and we will send it to you by email.</p>
                    <p>If you can't find the feature you need on our <a href="{% url 'features:features_list' %}">Features</a> page, you can request one using <a href="{% url 'features:feature_add' %}">Request a Feature</a> button.</p>
                </section>
                <hr />
                <hr />
                <div class="card-body">
                    {% for feature in features %}
                    <h6 class="font-weight-bold">{{ feature.title }}
                        <small><span class="card-text text-muted float-right">Posted by <b>{{ feature.author }}</b> on {{ feature.created_on|date:"M d, Y" }} </span></small></h6>
                    <small>
                        <p class="card-text">{{ feature.content|slice:":50" }}</p>
                    </small>
                    <small><a href="{% url 'features:feature_detail' pk=feature.pk %}" class="btn-outline-info">Read More &rarr;</a><span class="alert-warning float-right">Price: <i class="fas fa-pound-sign"></i>{{ feature.price }}</span></small>
                    <hr />
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Bugs section -->
        <div class="col-md-4">
            <div class="card my-4">
                <h5 class="card-header text-center"><a class="nav-link font-weight-bold nav-font" href="{% url 'bugs:bugs_list' %}">Latest Bugs Posted <i class="fas fa-bug"></i></a></h5>
                <section class="alert alert_introduction alert-dismissible col-xs-12" role="alert">
                    <i class="fas fa-info-circle"></i>
                    <p>Bugs are free of charge. Have a look on the <a href="{% url 'bugs:bugs_list' %}">bugs list</a> to check if your bug have already been fixed. If you can't find it simply <a href="{% url 'bugs:bug_add' %}">Report a Bug</a>.
                    </p>
                </section>
                <hr />
                <hr />
                <div class="card-body">
                    {% for bug in bugs %}
                    <h6 class="font-weight-bold">{{ bug.title }}
                        <small><span class="card-text text-muted float-right">Posted by <b>{{ bug.author }}</b> on {{ bug.created_on|date:"M d, Y" }} </span></small></h6>
                    <small>
                        <p class="card-text">{{ bug.content|slice:":50" }}</p>
                    </small>
                    <small><a href="{% url 'bugs:bug_detail' pk=bug.pk %}" class="btn-outline-info">Read More &rarr;</a></small>
                    <hr />
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Blog section -->
        <div class="col-md-3 float-right">
            <div class="card my-4">
                <h5 class="card-header text-center"><a class="nav-link font-weight-bold nav-font" href="{% url 'blog:blog' %}">Latest from the Blog <i class="fas fa-blog"></i></a></h5>
                <div class="card-body">
                    {% for post in blogs %}
                    <h6 class="font-weight-bold pb-1">{{ post.title }}</h6>
                    <small><span class="card-text text-muted">Posted by <b>{{ post.author }}</b> on {{ post.created_on|date:"M d, Y" }}</span></small>
                    <!--<p class="card-text pb-0">{{post.content|slice:":50" }}</p>-->
                    <small><a href="{% url 'blog:post_detail' slug=post.slug %}" class="btn-outline-info">Read More &rarr;</a></small>
                    <hr />
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% block charts %} {% include 'charts.html' %} {% endblock charts %}
</div>

{% endblock %}

templates/sidebar.html
{% block sidebar %}

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
    <h5 class="card-header card-head-cust"><i class="far fa-user-circle"></i>   Your profile</h5>
    <div class="card-body card-body-cust">
    	<p>You are logged in as: </p>
    	<p>Username: <i>{{ user.username }}</i></p>
    	<p>Email: <i>{{ user.email }}</i></p>
    </div>
</div>
</div>

{% endblock sidebar %}